FROM python:3.7

RUN mkdir /var/www
WORKDIR /var/www

COPY --chown=root:root requirements.txt .
COPY --chown=root:root uwsgi.ini .

ENV FLASK_PORE_NUM 80

RUN pip install -U pip
RUN pip install --no-cache-dir -r requirements.txt

CMD ["uwsgi", "--ini", "uwsgi.ini:socket"]
